vercel/next-learn

api-routes-starter/components/layout.js
basics-final/components/layout.js
data-fetching-starter/components/layout.js
dynamic-routes-starter/components/layout.js
dynamic-routes-step-1/components/layout.js
typescript-final/components/layout.tsx

Merge this after https://github.com/zeit/next-site/pull/638 is merged.

Add twitter card required attributes

---

api-routes-starter/package.json
assets-metadata-css-starter/package.json
basics-final/package.json
data-fetching-starter/package.json
demo/package.json
dynamic-routes-starter/package.json
dynamic-routes-step-1/package.json
learn-starter/package.json
navigate-between-pages-starter/package.json
typescript-final/package.json

Updated the Next.js learn starter to Next.js 10

updated the next-js learn starter to next-js 10

---

README.md
api-routes-starter/components/layout.js
api-routes-starter/components/layout.module.css
basics-final/components/layout.js
basics-final/components/layout.module.css
data-fetching-starter/components/layout.js
data-fetching-starter/components/layout.module.css
demo/components/layout.js
demo/components/layout.module.css
dynamic-routes-starter/components/layout.js
dynamic-routes-starter/components/layout.module.css
dynamic-routes-step-1/components/layout.js
dynamic-routes-step-1/components/layout.module.css
typescript-final/components/layout.module.css
typescript-final/components/layout.tsx

- Update all references to images to use `next/image`
- Replace all `.now.sh` URLs with `.vercel.app` (I added the alias already)
- Remove unused styles
Dependent on the corresponding PR to update `/learn` (in progress)

Use `next/image` and Image Optimization.

---

basics/errors/install.md

After following the docs in https://nextjs.org/learn/basics/create-nextjs-app/setup, I had an issue while running that command, and I followed the link, which contained a different command than the one shown in the doc.
Maybe it's out of date here. Of not, feel free to close the PR.

Update command as shown in docs

---

basics/learn-starter/pages/index.js

fix typo some prettiers complain about

Fix style/typo in index.js example

---

dashboard/15-final/app/dashboard/invoices/create/page.tsx
dashboard/15-final/app/ui/card.tsx
dashboard/15-final/app/ui/hero.tsx
dashboard/15-final/app/ui/invoice-form.tsx
dashboard/15-final/app/ui/login-form.tsx
dashboard/15-final/app/ui/revenue-chart.tsx
dashboard/15-final/app/ui/search.tsx
dashboard/15-final/package-lock.json
dashboard/15-final/package.json
dashboard/15-final/tailwind.config.ts

To reduce complexity, the form accepts two fields: 
```
customerId: 
amount:
```
The following are automatically generated: 
```
id: 1, // Record ID will be automatically incremented
status: "pending", // Default status for a new invoice
date: new Date().toISOString().split("T")[0], // Today's date
```

Add "create" invoice form

---

dashboard/15-final/app/dashboard/invoices/[id]/page.tsx
dashboard/15-final/app/lib/calculations.tsx
dashboard/15-final/app/lib/dummy-data.tsx
dashboard/15-final/app/ui/customers/table.tsx
dashboard/15-final/app/ui/dashboard/overview.tsx
dashboard/15-final/app/ui/invoices/table.tsx

This PR:
- Moves `totalInvoices()` to `calculations.tsx`
- Adds new calculation for total pending / paid invoices for each customer

Add total paid/pending columns to customer table

---

basics/assets-metadata-css-starter/pages/index.js
basics/errors/install.md
basics/learn-starter/pages/index.js
basics/navigate-between-pages-starter/pages/index.js

Addresses some comments left in #60.

Updates GitHub urls and adds a note about a `Could not locate the repository` error message

---

basics/assets-metadata-css-starter/styles/globals.css
basics/learn-starter/styles/globals.css
basics/navigate-between-pages-starter/styles/globals.css

Not sure how these extra styles snuck into different parts of the current course. The course itself doesn't teach adding it. I tried them out and decided they looked worse than what is in the demo, so we're going with the demo styles and thus removing them.
Fixes #106

Fixes inconsistent CSS

---

dashboard/15-final/app/page.tsx
dashboard/15-final/package.json

- Update landing page text to match design
- Remove weird ` <a> <button>` JSX

Update landing page text

---

dashboard/15-final/app/dashboard/(overview)/page.tsx
dashboard/15-final/app/lib/data.ts

- Combining SQL queries for card data into one function. The user won't have to edit this function, they just need to import it.

Combine data fetches for cards

---

dashboard/starter-example/README.md

This is very minimal change, there was a small error in the README.md of Starter-example. Please review changes.

Fix Starter-example README.md

---

dashboard/final-example/middleware.ts

Fix Middleware matcher to make profile pics work

---

dashboard/starter-example/app/page.tsx

Fixes: https://github.com/vercel/next-learn/issues/363

Add missing Arrow Icon to starter example

---

dashboard/final-example/scripts/seed.js
dashboard/starter-example/scripts/seed.js

Fix the typo in the comments of seed.js

---

dashboard/final-example/app/page.tsx

Update page.tsx - fix alt attribute for hero image

---

dashboard/final-example/app/lib/data.ts
dashboard/final-example/auth.ts
dashboard/starter-example/app/lib/data.ts

Fix formatting of  a few SQL queries to fit conventions, as pointed out here #390

Fix SQL formatting convention (#390)

---

dashboard/final-example/app/lib/data.ts
dashboard/starter-example/app/lib/data.ts

Relating to: https://github.com/vercel/next-learn/pull/378

Fix typo in code comment, polish wording

---

dashboard/starter-example/app/ui/invoices/table.tsx

Issue: https://github.com/vercel/next-learn/issues/480
Otherwise it breaks the build on vercel when following [Connect and deploy your project](https://nextjs.org/learn/dashboard-app/setting-up-your-database#connect-and-deploy-your-project) on Chapter 6

Fixes #480. Add missing alt attribute that breaks build

---

dashboard/final-example/app/ui/search.tsx

Add missing type.
This chapter also contains some inconsistencies in the text. Can we suggest improvements in that regard?

Fix missing type

---

dashboard/starter-example/app/ui/dashboard/latest-invoices.tsx

Chapter to uncomment was 7 instead of 9

Correct latest-invoice.tsx chapter reference

---

dashboard/starter-example/app/ui/invoices/pagination.tsx

Chapter to uncomment was 7 instead of 11

Correct pagination.tsx chapter reference

---

dashboard/final-example/app/query/route.ts
dashboard/starter-example/app/query/route.ts

In the last commit [46d15fa ](https://github.com/vercel/next-learn/commit/46d15fa2e58da6e25132b74846fddc022558f2b0) - again app/query/route.ts was deleted.
Restored and changed provider to agnostic postgre as it was done in last commit in other places.
Fixes issue #929

Fixed missing query files
