learn-starter/pages/index.js

the former text was "Vercel logo"; however "logo" doesn't much make sense in the context of "Powered by **" phrase.
https://html.spec.whatwg.org/multipage/images.html#a-short-phrase-or-label-with-an-alternative-graphical-representation:-icons,-logos
https://webaim.org/techniques/alttext/#logos

update alternative text for Vercel logo to just "Vercel"

---

api-routes-starter/package.json
assets-metadata-css-starter/package.json
basics-final/package.json
data-fetching-starter/package.json
demo/package.json
dynamic-routes-starter/package.json
dynamic-routes-step-1/package.json
learn-starter/package.json
navigate-between-pages-starter/package.json
typescript-final/next-env.d.ts
typescript-final/package.json

This updates to the latest Version of Next.js v11 and also bumps to latest react as well since I noticed these versions were out of date while looking into https://github.com/vercel/next.js/issues/27298

Update next/react versions

---

basics/assets-metadata-css-starter/styles/Home.module.css
basics/assets-metadata-css-starter/styles/globals.css

We've received some feedback that the styles folder is missing
Examples
- https://github.com/vercel/feedback/issues/22164
- https://github.com/vercel/feedback/issues/22162
I've copied the styles folder from the `seo` example

Add styles folder to Assets, Metadata, and CSS Example

---

basics/navigate-between-pages-starter/pages/index.js

Make it consistent with the changes the user has made in the first part of the tutorial "Create a Next.js App".  Also some changes required in the learn nextjs docs ( Which for some reason are not editable in github?) 
from 
```
<h1 className="title">
Welcome to <a href="https://nextjs.org">Next.js!</a>
</h1>
```
To 
```
<h1 className={styles.title}>
Learn <a href="https://nextjs.org">Next.js!</a>
</h1>
```
Also relates to this issue
https://github.com/vercel/next.js/issues/47479

Consistency between part 1 and 2 of the tutorial

---

dashboard/15-final/app/ui/invoices/pagination.tsx
dashboard/15-final/app/ui/invoices/table-search.tsx
dashboard/15-final/app/ui/invoices/table.tsx

In this PR I drill the `searchParams` from the page into the search component and pagination component so that we do not need to use `useSearchParams`. This means I was also able to remove the unnecessary state from the search component. I also removed `useTransition` and the loading state from the search component to simplify the code.

Remove unnecessary search state

---

dashboard/15-final/app/dashboard/customers/page.tsx
dashboard/15-final/app/dashboard/invoices/page.tsx
dashboard/15-final/app/lib/utils.ts
dashboard/15-final/app/ui/invoices/pagination.tsx
dashboard/15-final/app/ui/search.tsx

This PR fixes the pagination bugs:
1. We were using `pointer-events-none` to disable arrows for the first and last pages, but this only disables mouse events - keyboard users could navigate to `page=0` or `page=totalPages + 1`. This PR truly disables them by rendering a `<div>` instead of a `<Link>`. It also means we're not passing a href to disabled links.  
2. Fixes hover states. Removes hover state on active items, removes hover state on disabled items.
3. Disable ellipsis.  
4. Fixes border styles.
5. Fix bug where you could not click on subsequent pages if a search term existed (since the page would always default to 1)
I've also extracted away the logic into separate components to make it easier for the user to update the `<Pagination>` component.

Fix pagination bugs and refactor/abstract styling logic

---

dashboard/15-final/app/dashboard/invoices/[id]/edit/page.tsx
dashboard/15-final/app/dashboard/invoices/create/page.tsx
dashboard/15-final/app/dashboard/invoices/page.tsx
dashboard/15-final/app/ui/invoices/breadcrumbs.tsx
dashboard/15-final/app/ui/invoices/create-form.tsx
dashboard/15-final/app/ui/invoices/edit-form.tsx
dashboard/15-final/app/ui/invoices/pagination.tsx
dashboard/15-final/app/ui/search.tsx

Move breadcrumbs from the `<Form>` up to the `<Page>` as the user will be updating the forms - want to reduce code shown on snippets. Might make more sense to keep the breadcrumbs logic on the page.

Move breadcrumbs from <Form> up to the <Page>

---

dashboard/15-final/app/dashboard/invoices/[id]/edit/page.tsx
dashboard/15-final/app/dashboard/invoices/create/page.tsx
dashboard/15-final/app/lib/actions.ts
dashboard/15-final/app/lib/data.ts
dashboard/15-final/app/lib/definitions.ts
dashboard/15-final/app/ui/invoices/breadcrumbs.tsx
dashboard/15-final/app/ui/invoices/create-form.tsx
dashboard/15-final/app/ui/invoices/edit-form.tsx

Please merge this PR first: https://github.com/vercel/next-learn/pull/208
- Remove console warnings by using `MozAppearance` instead of `'-moz-appearance'`
- Pass `id` to edit-form `formData` using hidden input field - this was removed with the recent styling changes
- Pass `id` to customer input instead of `name`. Dropdown was always showing the first customer, it now shows the customer the specific invoice belongs to. 
- Move `redirect` outside the try/catch block as it's now throwing a Next.js error. Related: https://github.com/vercel/next.js/issues/55586

Fix form bugs

---

dashboard/final-example/app/lib/data.ts
dashboard/final-example/next.config.js

Fixes: https://github.com/vercel/next-learn/issues/277
- Remove PPR flag as it doesn't work in production yet
- Add `noStore` to `fetchInvoiceById` to fetch fresh data when the user visits the edit invoice route. 
- Update code snippet in the chapter: https://github.com/vercel/front/pull/26672
I don't think we need to call `revalidatePath` to purge the client-side router cache, but if this issue happens again, we can explore using `revalidateTag` instead.

Remove PPR flag, add `noStore` to `fetchInvoiceById`

---

dashboard/final-example/.eslintrc.json
dashboard/final-example/package-lock.json
dashboard/final-example/package.json
dashboard/starter-example/.eslintrc.json
dashboard/starter-example/package-lock.json
dashboard/starter-example/package.json

Fixes: https://github.com/vercel/next-learn/issues/304
This PR fixes an issue with running eslint in the `starter-example` and `final-example`  for Chapter 14. . Since we're setting the eslint config at the root of `next-learn`, running `npm run eslint` in the `starter-example` repo didn't automatically install the necessary packages and create the `eslintrc.json` file. 
- Installs eslint dependencies as devDependencies in `starter-example` and `final-example` repos
- Adds `.eslintrc.json` files
When running `next-learn` from the root, this setup will not work, and will give the following error: 
However, since the user will only clone the `starter-example`, this should work for their local repo.

Fix ESLint

---

dashboard/final-example/app/ui/invoices/create-form.tsx
dashboard/final-example/app/ui/invoices/edit-form.tsx
dashboard/starter-example/app/ui/invoices/create-form.tsx
dashboard/starter-example/app/ui/invoices/edit-form.tsx

This fixes an incorrect use of the `<label>` tag with a radio group. Moreover, the `htmlFor` attribute on the label pointed to an inexistent `id`.

fix: remove incorrect labels in radio groups

---

dashboard/final-example/scripts/seed.js
dashboard/starter-example/scripts/seed.js

This PR fixes a pooling issue users were experiencing when running the `seed.js` script: https://github.com/vercel/next-learn/issues/306
- `sql` opens a new connection when called. 
- Since we used `Promise.all` to seed the database, the script was creating multiple connections in parallel. 
- A user found a fix using `for` loops instead of `Promise.all` ([here](https://github.com/vercel/next-learn/issues/306#issuecomment-1785766539)), however this doesn't prevent multiple connections from being opened - they are just opened sequentially. 
With this PR, we open a single connection with `db.connect()`, run our seeding scripts, then close the connection. 
```
async function main() {
const client = await db.connect();
await seedUsers(client);
await seedCustomers(client);
await …
```

Fix connection pooling with `seed.js` script

---

dashboard/final-example/app/dashboard/(overview)/page.tsx
dashboard/final-example/app/ui/dashboard/cards.tsx
dashboard/starter-example/app/ui/dashboard/cards.tsx

Having two components with similar names: `<Card>` and `<Cards/>` was confusing. This changes `<Cards/>` to `<CardWrapper/>` to be more clear on what the component is doing. 
Fixes: https://github.com/vercel/next-learn/issues/273

Rename Cards component to CardWrapper

---

dashboard/starter-example/app/lib/data.ts

The steps in [Chapter 12, Step 3](https://nextjs.org/learn/dashboard-app/mutating-data#3-fetch-the-specific-invoice) of the dashboard tutorial result in a TypeScript error on the `invoice` prop of the edit invoice form. In the completed example there's an error thrown in the `catch` block, but in the starter project it is absent resulting in an error in the inferred function return type.

fix: throw new error in `fetchInvoiceById` catch block

---

dashboard/final-example/app/ui/invoices/create-form.tsx
dashboard/final-example/app/ui/invoices/edit-form.tsx
dashboard/final-example/app/ui/login-form.tsx

The `aria-live` region for form errors needs to be present in the DOM to allow screen readers to monitor changes. This PR updates the structure, and moves the label outside the conditional. 
More context: https://github.com/vercel/next-learn/issues/418
See also: https://dev.to/abbeyperini/live-regions-in-react-4dmd
PR to update the chapter: https://github.com/vercel/front/pull/27101

Improve Form Error Accessibility 

---

dashboard/final-example/app/ui/invoices/create-form.tsx
dashboard/final-example/app/ui/invoices/edit-form.tsx
dashboard/starter-example/app/ui/invoices/create-form.tsx
dashboard/starter-example/app/ui/invoices/edit-form.tsx

Closes: https://linear.app/vercel/issue/DX-2204/fix-pendingpaid-radio-buttons-in-create-formtsx-and-edit-formtsx
We had some `dark:` tailwind classes in the forms, meaning if your system preference was set to dark, the radio input would look like this: 
This PR removes the `dark` classes so that even if the user's preference is dark, it'll display the correct colors:

Fix radio input when system preference is set to dark

---

dashboard/final-example/app/lib/actions.ts
dashboard/final-example/app/ui/login-form.tsx
dashboard/final-example/package.json

This PR bumps NextAuth.js to the latest version.
The main noticeable change is cleaner error handling: Whenever a NextAuth.js-induced error happens in a Server Action, we now throw an [`AuthError` instance](https://authjs.dev/reference/core/errors#autherror) that makes error handling a bit easier.
In addition, this new release includes bug fixes. See the release notes: https://github.com/nextauthjs/next-auth/releases/tag/next-auth%405.0.0-beta.4
[Slack thread](https://vercel.slack.com/archives/C05KP92R51B/p1701179666546759)

chore: bump `next-auth`

---

dashboard/final-example/app/ui/skeletons.tsx
dashboard/starter-example/app/ui/skeletons.tsx

All this fix does is moving closing `</div>` tag in the `LatestInvoicesSkeleton` component so that the skeleton looks as close as the actual `LatestInvoices` component
Skeleton before:
Skeleton after:
Component:

Fix: make UI skeleton more similar to the actual component

---

dashboard/final-example/app/ui/invoices/pagination.tsx

Using only the page as a key does not preserve uniqueness across updates. This caused, for example, an ellipsis to appear before the pagination elements when navigating from a page in the middle of the results back to the first page.

Add index to Pagination key for uniqueness

---

dashboard/final-example/app/lib/data.ts
dashboard/starter-example/app/lib/data.ts

`getUser` implementation got moved to `@app/lib/data`:
- #212 
However, during the update of `auth.ts`, somehow `getUser` got decided to retained in `auth.ts` (which might be a result of a git conflict or intended to bundle seperatly)
- #219
and the one that moved in `@app/lib/data` was not removed.
1. `getUser` in the `@app/lib/data` is no longer in use.
2. Chapter 15 describes upon the one in `auth.ts`
Therefore, shouldn't we remove the unused one left in  `@app/lib/data` unless it was unintentional ?
or we could consider removing the one in `auth.ts` with updating Chapter 15 mdx (don't forget to update type assertion to generic.)
In any case, one of them should be removed.
Thank you for the amazing course.

Remove unused getUser

---

dashboard/starter-example/app/ui/dashboard/cards.tsx
dashboard/starter-example/app/ui/dashboard/latest-invoices.tsx
dashboard/starter-example/app/ui/dashboard/revenue-chart.tsx
dashboard/starter-example/app/ui/invoices/pagination.tsx

Improve clarity for code that needs to be uncommented.  
Related: https://github.com/vercel/next.js/issues/67225

Update code comments

---

dashboard/starter-example/app/query/route.ts

add an example `/query` route to replace the Vercel Postgres Data Browser/Query, which is not available for the other Marketplace Postgres providers (Supabase, Neon)

add example query

---

dashboard/starter-example/app/ui/customers/table.tsx
dashboard/starter-example/app/ui/dashboard/latest-invoices.tsx
dashboard/starter-example/app/ui/dashboard/revenue-chart.tsx

Hello, this fix issue #893
Removal of the three unused definition and additional code using `error` param in the Chapter 13 in try catch will truly output
` ✔ No ESLint warnings or errors`

Fix ESLint Error defined but never used in Chapter 14

---

dashboard/starter-example/app/ui/customers/table.tsx
dashboard/starter-example/app/ui/dashboard/latest-invoices.tsx
dashboard/starter-example/app/ui/dashboard/revenue-chart.tsx

Revert "Fix ESLint Error defined but never used in Chapter 14"

---

dashboard/final-example/app/login/page.tsx
dashboard/final-example/app/ui/dashboard/sidenav.tsx
dashboard/final-example/app/ui/login-form.tsx
dashboard/final-example/package.json
dashboard/final-example/pnpm-lock.yaml
dashboard/starter-example/package.json
dashboard/starter-example/pnpm-lock.yaml

Fixes https://github.com/vercel/next-learn/issues/861

Update auth chapter

---

dashboard/starter-example/app/ui/invoices/pagination.tsx

While following the dashboard tutorial, I identified that the `Pagination` component in the `starter-example` uses an incorrect `key` prop, which could cause potential issues with React's list rendering.
This issue has already been corrected in the `final-example` code, as seen in PR #640.
This pull request updates the `starter-example` to use the correct `key` prop, consistent with the fix in the `final-example` . This ensures learners starting the tutorial won't encounter this discrepancy as they uncomment the code step-by-step.

fix: Add index to Pagination key for uniqueness in starter-example

---

dashboard/final-example/app/query/route.ts
dashboard/final-example/package.json
dashboard/final-example/pnpm-lock.yaml
dashboard/starter-example/package.json
dashboard/starter-example/pnpm-lock.yaml

Since we are using `pnpm`, we have to allow `bcrypt` to be built. 
I think we should maybe switch to `bcryptjs`, https://github.com/vercel/next.js/discussions/76822
Closes: https://linear.app/vercel/issue/DOC-4032/update-learn-to-use-153-latest

Upgrade packages in next-learn/dashboard

---

dashboard/final-example/package.json
dashboard/starter-example/package.json

Closes: https://linear.app/vercel/issue/DOC-4032/update-learn-to-use-153-latest
Complementary, also add `sharp` to be a `pnpm` built dependency.

chore: add sharp to pnpm built dependencies
